# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: churumelas
  user: jonatasdp
  password:

test:
  adapter: mysql2
  database: churumelas_test
  user: jonatasdp

production:
  adapter: mysql2 
  database: churumelas_production
  user: root
  password: churumelas
